Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\dsm_book\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\ProgramData\Anaconda3\envs\dsm_book\lib\site-packages\nbclient\client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\ProgramData\Anaconda3\envs\dsm_book\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\ProgramData\Anaconda3\envs\dsm_book\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "C:\ProgramData\Anaconda3\envs\dsm_book\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\ProgramData\Anaconda3\envs\dsm_book\lib\site-packages\nbclient\client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "C:\ProgramData\Anaconda3\envs\dsm_book\lib\site-packages\nbclient\client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "C:\ProgramData\Anaconda3\envs\dsm_book\lib\site-packages\nbclient\client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
churnSample <- read_csv("_build/data/churn_sample.csv")
churnSample$account_length <- (churnSample$account_length - min(churnSample$account_length)) / (max(churnSample$account_length) - min(churnSample$account_length))
churnSample$total_intl_charge <- (churnSample$total_intl_charge - min(churnSample$total_intl_charge)) / (max(churnSample$total_intl_charge) - min(churnSample$total_intl_charge))
# get the range of x1 and x2
rx1 <- range(churnSample$account_length)
rx2 <- range(churnSample$total_intl_charge)
# get lattice points in predictor space
px1 <- seq(from = rx1[1], to = rx1[2], by = 0.015 )
px2 <- seq(from = rx2[1], to = rx2[2], by = 0.015 )
xnew <- expand.grid(x1 = px1, x2 = px2)

# get the contour map
k=5
knnK <- knn(train = churnSample[,1:2], test = xnew, cl = churnSample$churn, k = k, prob = TRUE)
prob <- attr(knnK, "prob")
prob <- ifelse(knnK=="1", prob, 1-prob)
probK <- matrix(prob, nrow = length(px1), ncol = length(px2))

# Figure 2.2
#par(mar = rep(2,4))
contour(px1, px2, probK, levels=0.5, labels="", xlab="account_length", ylab="total_intl_charge", axes=FALSE)
points(churnSample[,1:2], col=ifelse(churnSample[,3]==1, "#F8766D", "#00BFC4"),
       pch=ifelse(churnSample[,3]==1, 19, 17))
points(xnew, pch=".", cex=1.2, col=ifelse(probK>0.5, "#F8766D", "#00BFC4"),
       shape=ifelse(churnSample[,3]==1, "a", "b"))
title(xlab="account_length", ylab="total_intl_charge", main=paste0("k = ", k))
box()
------------------

Error: '_build/data/churn_sample.csv' does not exist in current working directory ('C:/Users/phamilton/Documents/dsm/jupyter_book').
Traceback:

1. read_csv("_build/data/churn_sample.csv")
2. read_delimited(file, tokenizer, col_names = col_names, col_types = col_types, 
 .     locale = locale, skip = skip, skip_empty_rows = skip_empty_rows, 
 .     comment = comment, n_max = n_max, guess_max = guess_max, 
 .     progress = progress)
3. standardise_path(file)
4. check_path(path)
5. stop("'", path, "' does not exist", if (!is_absolute_path(path)) paste0(" in current working directory ('", 
 .     getwd(), "')"), ".", call. = FALSE)
ERROR: Error: '_build/data/churn_sample.csv' does not exist in current working directory ('C:/Users/phamilton/Documents/dsm/jupyter_book').


